name: MonnetalX

on:
  issues:
    types: [opened]

jobs:
  respond-to-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    
    steps:
      - name: Run JaoMonnBot
        # uses: AruzCandlr/MonnAboveTest@monnmonnXD.v3
        # uses: AruzCandlr/MonnAboveTest@gemimonnnn
        uses: AruzCandlr/MonnAboveTest@mockmonnX
        with:
          openai_api_key: ${{ secrets.API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.issue.number }}
          repo: ${{ github.repository }}
