name: MonnetalX

on:
  # issues:
    # types: [opened]
  pull_request
  
jobs:
  respond-to-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    
    steps:
      - name: Run JaoMonnBot
        # uses: AruzCandlr/MonnAboveTest@monnmonnXD.v3
        # uses: AruzCandlr/MonnAboveTest@gemimonnnn
        uses: AruzCandlr/MonnAboveTest@mockmonnX
        with:
          openai_api_key: ${{ secrets.API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.pull_request.number }}
          repo: ${{ github.repository }}
